### ISSUE TITLE
TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by OzReaction** [OzReaction/restServer#1]
/Users/stuarthall/restServer/app.js:19
MongoClient.connect(uri, function(err, db) {
            ^

TypeError: Cannot read property 'connect' of undefined
    at Object.<anonymous> (/Users/stuarthall/restServer/app.js:19:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/stuarthall/restServer/server.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Comment by OzReaction** [comment]
Resolved

  if ( error ) { console.error('Connection Failed');
    return console.log(error); }
  console.log("Connected");
  db.collection('Members').find().toArray(function(error,d) {
    if ( error ) { console.log('error'); console.log(e);  }
      console.log(d);
  });
    db.close();
});
